exec = hello.out
sources = $(wildcard src/*.c)
objects = $(sources:.c=.o)
flags = -g 


$(exec): $(objects)
	gcc $(objects) $(flasgs) -o $(exec)

%.o: %.c include/%.h
	gcc -c $(flags) $< -o $@

install:
	make
	cp ./hello.out /home/myprojects/CustomC

clean:
	-rm *.out
	-rm *.o
	-rm src/*.o
